### ISSUE TITLE
More updates

### ISSUE THREAD

**Issue by DittoRonaldo** [unknown321/mgsv_nuke_watcher#2]
Hi im new over here just wanna know is there anyway i can get like hourly updates or something like that? srry if this is not the appropiate way of communication

**Comment by unknown321** [comment]
you can query konami's api yourself every hour if you need to - see https://github.com/unknown321/mgsv_emulator

this repo used to have hourly updates, but:
  - repo was growing huge with 24 daily commits
  - it takes more resources to render these values on the page
  - I see no reason to get that data every hour, what for?
